<a href="https://colab.research.google.com/github/assyifahnurlaeli/assyifahnurlaeli/blob/Porto/Salinan_dari_%5BNEW%5D_Weekly_IDL_Only.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Corp Sales Reporting: Weekly**

In [192]:
# start_date and end_date
# edit start date and end date here
start_date = '2024-08-01'
end_date = '2025-08-17'

# edit weekly periode here (for rename the files)
# periode = '29 Juli  - 04 Agustus 2024'
url_dump = 'https://docs.google.com/spreadsheets/d/1Ok4hXiWec0haX4Jpr90F_bhUTRhhq1NX4ExvXfAKrwc/edit?gid=0#gid=0'

In [193]:
import os
import requests
import time
# from pprint import pprint
import json
import pandas as pd
import sys
from datetime import datetime,timedelta
start_time = datetime.now()
import numpy as np
# from google.colab import drive


from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from smtplib import SMTP
import ssl
import smtplib
!pip install pretty_html_table
from pretty_html_table import build_table

# drive.mount('/drive')

def poll_job(s, redash_url, job):
    # TODO: add timeout
    while job['status'] not in (3,4):
        response = s.get('{}/api/jobs/{}'.format(redash_url, job['id']))
        job = response.json()['job']
        time.sleep(5)

    if job['status'] == 3:
        return job['query_result_id']

    return None


def get_fresh_query_result(redash_url, query_id, api_key, params):
    s = requests.Session()
    s.headers.update({'Authorization': 'Key {}'.format(api_key)})

    payload = dict(max_age=0, parameters=params)

    response = s.post('{}/api/queries/{}/results'.format(redash_url, query_id), data=json.dumps(payload))

    if response.status_code != 200:
        return 'Refresh failed'
        raise Exception('Refresh failed.')

    result_id = poll_job(s, redash_url, response.json()['job'])

    if result_id:
        while True:
            try:
                response = s.get('{}/api/queries/{}/results/{}.json'.format(redash_url, query_id, result_id))
                break
            except:
                print('retry')

        if response.status_code != 200:
            raise Exception('Failed getting results.')
    else:
        raise Exception('Query execution failed.')

    return response.json()['query_result']['data']['rows']

Requirement already satisfied: pretty_html_table in /usr/local/lib/python3.12/dist-packages (0.9.16)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from pretty_html_table) (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas->pretty_html_table) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->pretty_html_table) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->pretty_html_table) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->pretty_html_table) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->pretty_html_table) (1.17.0)

## List Shipper
update list shipper here

In [194]:
# # FORMAT:
# # list = [
# #     [id,nama shipper]

# # ]

# # update list shipper here
# list_shipper = [
#     [5383720,'PT.Saraswanti Indo Genetech (Corp DS)'],
#     [5372948,'PT Dwi Cermat Indonesia (Corp Ds)'],
#     [8190204,'KPP PRATAMA Pontianak Timur (Reg Docs)'],
#     [7682184,'KPP PRATAMA PONTIANAK BARAT (Reg Docs)'],
#     [5819428,'KPP Pratama Bantaeng (Reg Docs)'],
#     [8193861,'KPP Pratama Palopo (Reg Docs)'],
#     [8018264,'PT Suntone Teknologi International (Corp DS)'],
#     [10317451,'PT Indotama Domestik Lestari']
# ]


# listglobal_shipper_id = []
# for i in list_shipper:
#   listglobal_shipper_id.append(i[0])

# listShipper = ",".join(map(str, listglobal_shipper_id))

## Pull Data from Redash 245

In [195]:
from datetime import datetime, timedelta

# start_date tetap manual
start_date = '2024-08-01'

# cari hari ini
today = datetime.today()

# cari selisih ke Minggu terakhir
offset = (today.weekday() - 6) % 7
last_sunday = today - timedelta(days=offset)

# end_date = Minggu terakhir
end_date = last_sunday.strftime("%Y-%m-%d")

print("Start Date:", start_date)
print("End Date (last Sunday):", end_date)

Start Date: 2024-08-01
End Date (last Sunday): 2025-09-14

In [196]:
raw_data.columns

Index(['order_creation_datetime', 'order_id', 'tracking_id',
       'global_shipper_id', 'shipper_name', 'shipper_reference_no', 'emboss',
       'from_address', 'to_address', 'original_delivery_address', 'rts_flag',
       'granular_status', 'to_name', 'to_contact', 'original_name_1',
       'original_delivery_address_1', 'original_email_1', 'original_contact_1',
       'original_name_2', 'original_delivery_address_2', 'original_email_2',
       'original_contact_2', 'original_name_3', 'original_delivery_address_3',
       'original_email_3', 'original_contact_3', 'instruction',
       'order_comments', 'pickup_datetime', 'first_inbound_datetime',
       'cod_value', 'pod_datetime', 'pod_recipient_name',
       'recipient_relationship', 'pod_photo_url', 'pod_signature_url',
       'first_attempt_at', 'first_fail_reason', 'last_attempt_at',
       'last_fail_reason', 'no_of_attempt'],
      dtype='object')

In [197]:
# grouping
bri = [[259335,'BRI Surabaya'], [292210,'BRI Kantor Pusat 2']]
siap_express = [2211259,'Siap Express (Corp Ds)']
mandiri = [[144426,'Mandiri Tunas Finance Garut (Corp DS)'], [235840,'PT Mandiri Tunas Finance Cab. Cikarang (Corp DS)']]

# adjust columns
raw = raw_data[['order_creation_datetime','tracking_id','global_shipper_id','shipper_name','shipper_reference_no','from_address','to_address','rts_flag','granular_status','to_name',
                    'to_contact','instruction','order_comments','pickup_datetime','first_inbound_datetime','pod_datetime','pod_recipient_name','recipient_relationship','pod_photo_url',
                    'pod_signature_url','first_attempt_at','first_fail_reason','last_attempt_at','last_fail_reason','no_of_attempt','cod_value']]

In [198]:
raw['start_clock_datetime'] = raw.apply(lambda row: row['pickup_datetime'] if pd.notnull(row['pickup_datetime']) else row['first_inbound_datetime'], axis=1)

/tmp/ipython-input-57836387.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  raw['start_clock_datetime'] = raw.apply(lambda row: row['pickup_datetime'] if pd.notnull(row['pickup_datetime']) else row['first_inbound_datetime'], axis=1)

In [199]:
raw['start_clock_datetime'] = pd.to_datetime(raw['start_clock_datetime'])
raw['first_attempt_at'] = pd.to_datetime(raw['first_attempt_at'])

/tmp/ipython-input-3028859860.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  raw['start_clock_datetime'] = pd.to_datetime(raw['start_clock_datetime'])
/tmp/ipython-input-3028859860.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  raw['first_attempt_at'] = pd.to_datetime(raw['first_attempt_at'])

In [200]:
raw['actual_sla'] = (raw['first_attempt_at']-raw['start_clock_datetime']).dt.days

/tmp/ipython-input-126646395.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  raw['actual_sla'] = (raw['first_attempt_at']-raw['start_clock_datetime']).dt.days

## Shipper Group Format & Adjust Columns

In [201]:
raw.head()

,order_creation_datetime,tracking_id,global_shipper_id,shipper_name,shipper_reference_no,from_address,to_address,rts_flag,granular_status,to_name,...,pod_photo_url,pod_signature_url,first_attempt_at,first_fail_reason,last_attempt_at,last_fail_reason,no_of_attempt,cod_value,start_clock_datetime,actual_sla
0,2025-07-30T17:05:34,IDL250730087027,10317451,PT Indotama Domestik Lestari - Reguler (Corp DS),IDCB2507003068,PT Indotama Partner Logistics - Head Office Ka...,"Jl. Pluit Putra Raya No.5 , RT 11 RW 6 , Penja...",Non RTS,Completed,(IBU LIANA) PLUIT LIFESTYLE CENTRE (LIE FEI CH...,...,https://api.ninjavan.co/assets/d1f974a5-95fb-4...,https://api.ninjavan.co/assets/f7fc58e7-64e5-4...,2025-08-01 15:07:00,None,2025-08-01T15:07:00,None,1,None,2025-07-30 18:59:29,1.0
1,2025-07-30T17:05:34,IDL250730087030,10317451,PT Indotama Domestik Lestari - Reguler (Corp DS),IDCB2507003077,PT Indotama Partner Logistics - Head Office Ka...,"VILLA KALIJUDAN INDAH BLK J 17 TAMBAKSARI. , ...",Non RTS,Completed,AI FANG | +62-8113323196,...,https://api.ninjavan.co/assets/1a03e0c1-8dea-4...,https://api.ninjavan.co/assets/01db7f0d-5e0f-4...,2025-08-01 18:13:54,None,2025-08-01T18:13:54,None,1,None,2025-07-30 18:59:29,1.0
2,2025-07-30T17:05:35,IDL250730087016,10317451,PT Indotama Domestik Lestari - Reguler (Corp DS),IDCB2507003069,PT Indotama Partner Logistics - Head Office Ka...,"Jl. Pluit Putra Raya No.5 , RT 11 RW 6 , Penja...",Non RTS,Completed,(IBU LIANA) PLUIT LIFESTYLE CENTRE (SYLVIA HEN...,...,https://api.ninjavan.co/assets/d1f974a5-95fb-4...,https://api.ninjavan.co/assets/f7fc58e7-64e5-4...,2025-08-01 15:07:00,None,2025-08-01T15:07:00,None,1,None,2025-07-30 18:59:29,1.0
3,2025-07-30T17:05:36,IDL250730087099,10317451,PT Indotama Domestik Lestari - Reguler (Corp DS),IDCB2507003123,PT Indotama Partner Logistics - Head Office Ka...,"JL MARTADINATA 24 , SUDIROPRAJAN , Jebres - Ko...",Non RTS,Completed,MARIA ANNA | +62-8174711796,...,https://api.ninjavan.co/assets/f178a36c-9395-4...,https://api.ninjavan.co/assets/f6e32851-26c7-4...,2025-08-01 14:47:42,None,2025-08-01T14:47:42,None,1,None,2025-07-30 18:59:29,1.0
4,2025-07-30T17:05:37,IDL250730087079,10317451,PT Indotama Domestik Lestari - Reguler (Corp DS),IDCB2507003124,PT Indotama Partner Logistics - Head Office Ka...,"ANIVA GRANDE GA/07, GADING SERPONG, PAGEDANGAN...",Non RTS,Completed,MUTIARA | +62 838‑9894‑5434,...,https://api.ninjavan.co/assets/40a52c92-7555-4...,https://api.ninjavan.co/assets/ff551118-b6ba-4...,2025-08-01 14:48:53,None,2025-08-01T14:48:53,None,1,None,2025-07-30 18:59:29,1.0

In [202]:
# raw.to_csv("raw2.csv")

#**TARIK DATA FROM METABASE**

In [203]:
token = '9508f04e-faca-4273-82a5-0fe98f010d75'

In [204]:
print('Pull data from Metabase......')
from urllib.parse import quote
def tarik_metabase(link_metabase,parameters,token):
  # Fetch Metabase data
  url =  link_metabase
  headers = {
  'Content-Type': 'application/x-www-form-urlencoded',  # Change content type
  'X-Metabase-Session': token
  }
  params =  parameters

  # Convert the parameters to a JSON string with double quotes
  params_json = json.dumps(params)  # Use json.dumps to ensure proper JSON formatting

  # URL-encode the JSON string
  params_encoded = quote(params_json)

  # Format the payload as key=value
  payload = f"parameters={params_encoded}"

  response = requests.post(url, headers=headers, data=payload)


  if response.status_code == 200:
      data = pd.DataFrame(response.json())
      return data
      print(data)
  else:
      print(f"Failed to fetch data. Status code: {response.status_code}, Response: {response.text}")

parameters = [
  {
    "id": "148c69aa-0d63-4c4e-9edc-faca150c5534",
    "type": "date/all-options",
    "value": "2024-08-01~2025-09-07",
    "target": [
      "dimension",
      [
        "template-tag",
        "creation_datetime"
      ]
    ]
  },
  {
    "id": "d81c9d63-7560-4e14-b62e-4c0b7ecf7195",
    "type": "string/=",
    "value": [
      "10317451"
    ],
    "target": [
      "dimension",
      [
        "template-tag",
        "shipper_id"
      ]
    ]
  }
]

ssm_raw_data = tarik_metabase('https://metabase.ninjavan.co/api/card/98517/query/json',parameters, token)
print('Done.')
raw_ssm = pd.DataFrame(ssm_raw_data)
raw_ssm.head()

Pull data from Metabase......
Done.

,to_l2_name,tracking_id,creation_datetime,start_clock_datetime,pickup_datetime,actual_sla,order_creation,order_id,delivery_success_datetime,shipper_id,from_l2_name,granular_status,inbound_datetime,sla_days,flag,shipper_name
0,Kab. Banyumas,IDL250430045656,2025-05-02T16:52:07,2025-05-02T21:08:20,2025-05-02T21:08:20,2.0,2025-05-02,1482771972,2025-05-04T13:52:23,10317451,Kota Bekasi,Completed,2025-05-03T01:04:56,4.0,Hit,PT Indotama Domestik Lestari - Reguler (Corp DS)
1,Kab. Banyumas,IDL250430045629,2025-05-02T16:52:06,2025-05-02T21:08:19,2025-05-02T21:08:19,4.0,2025-05-02,1482771966,2025-05-06T14:15:32,10317451,Kota Bekasi,Completed,2025-05-03T00:11:28,4.0,Hit,PT Indotama Domestik Lestari - Reguler (Corp DS)
2,Kab. Blora,IDL250502043666,2025-05-02T16:52:08,2025-05-02T21:08:18,2025-05-02T21:08:18,4.0,2025-05-02,1482772006,2025-05-06T14:04:46,10317451,Kota Bekasi,Completed,2025-05-03T00:11:37,4.0,Hit,PT Indotama Domestik Lestari - Reguler (Corp DS)
3,Kab. Jember,IDL250430045666,2025-05-02T16:52:07,2025-05-02T21:08:20,2025-05-02T21:08:20,2.0,2025-05-02,1482771985,2025-05-04T12:43:07,10317451,Kota Bekasi,Completed,2025-05-03T01:03:29,4.0,Hit,PT Indotama Domestik Lestari - Reguler (Corp DS)
4,Kab. Jember,IDL250502043637,2025-05-02T16:52:07,2025-05-02T21:08:21,2025-05-02T21:08:21,3.0,2025-05-02,1482771993,2025-05-05T11:27:46,10317451,Kota Bekasi,Completed,2025-05-03T00:10:58,4.0,Hit,PT Indotama Domestik Lestari - Reguler (Corp DS)



```
# Ini diformat sebagai kode
```

# Add SLA Days and Flag

In [205]:
sla = raw_ssm

In [206]:
sla.head()

,to_l2_name,tracking_id,creation_datetime,start_clock_datetime,pickup_datetime,actual_sla,order_creation,order_id,delivery_success_datetime,shipper_id,from_l2_name,granular_status,inbound_datetime,sla_days,flag,shipper_name
0,Kab. Banyumas,IDL250430045656,2025-05-02T16:52:07,2025-05-02T21:08:20,2025-05-02T21:08:20,2.0,2025-05-02,1482771972,2025-05-04T13:52:23,10317451,Kota Bekasi,Completed,2025-05-03T01:04:56,4.0,Hit,PT Indotama Domestik Lestari - Reguler (Corp DS)
1,Kab. Banyumas,IDL250430045629,2025-05-02T16:52:06,2025-05-02T21:08:19,2025-05-02T21:08:19,4.0,2025-05-02,1482771966,2025-05-06T14:15:32,10317451,Kota Bekasi,Completed,2025-05-03T00:11:28,4.0,Hit,PT Indotama Domestik Lestari - Reguler (Corp DS)
2,Kab. Blora,IDL250502043666,2025-05-02T16:52:08,2025-05-02T21:08:18,2025-05-02T21:08:18,4.0,2025-05-02,1482772006,2025-05-06T14:04:46,10317451,Kota Bekasi,Completed,2025-05-03T00:11:37,4.0,Hit,PT Indotama Domestik Lestari - Reguler (Corp DS)
3,Kab. Jember,IDL250430045666,2025-05-02T16:52:07,2025-05-02T21:08:20,2025-05-02T21:08:20,2.0,2025-05-02,1482771985,2025-05-04T12:43:07,10317451,Kota Bekasi,Completed,2025-05-03T01:03:29,4.0,Hit,PT Indotama Domestik Lestari - Reguler (Corp DS)
4,Kab. Jember,IDL250502043637,2025-05-02T16:52:07,2025-05-02T21:08:21,2025-05-02T21:08:21,3.0,2025-05-02,1482771993,2025-05-05T11:27:46,10317451,Kota Bekasi,Completed,2025-05-03T00:10:58,4.0,Hit,PT Indotama Domestik Lestari - Reguler (Corp DS)

In [207]:
sla.columns

Index(['to_l2_name', 'tracking_id', 'creation_datetime',
       'start_clock_datetime', 'pickup_datetime', 'actual_sla',
       'order_creation', 'order_id', 'delivery_success_datetime', 'shipper_id',
       'from_l2_name', 'granular_status', 'inbound_datetime', 'sla_days',
       'flag', 'shipper_name'],
      dtype='object')

In [208]:
sla_fix = sla[['tracking_id','sla_days']]

In [209]:
sla_fix.head()

       tracking_id  sla_days
0  IDL250430045656       4.0
1  IDL250430045629       4.0
2  IDL250502043666       4.0
3  IDL250430045666       4.0
4  IDL250502043637       4.0

In [210]:
final_data = raw.merge(sla_fix, on='tracking_id', how='left')

In [211]:
final_data.head()

,order_creation_datetime,tracking_id,global_shipper_id,shipper_name,shipper_reference_no,from_address,to_address,rts_flag,granular_status,to_name,...,pod_signature_url,first_attempt_at,first_fail_reason,last_attempt_at,last_fail_reason,no_of_attempt,cod_value,start_clock_datetime,actual_sla,sla_days
0,2025-07-30T17:05:34,IDL250730087027,10317451,PT Indotama Domestik Lestari - Reguler (Corp DS),IDCB2507003068,PT Indotama Partner Logistics - Head Office Ka...,"Jl. Pluit Putra Raya No.5 , RT 11 RW 6 , Penja...",Non RTS,Completed,(IBU LIANA) PLUIT LIFESTYLE CENTRE (LIE FEI CH...,...,https://api.ninjavan.co/assets/f7fc58e7-64e5-4...,2025-08-01 15:07:00,None,2025-08-01T15:07:00,None,1,None,2025-07-30 18:59:29,1.0,2.0
1,2025-07-30T17:05:34,IDL250730087030,10317451,PT Indotama Domestik Lestari - Reguler (Corp DS),IDCB2507003077,PT Indotama Partner Logistics - Head Office Ka...,"VILLA KALIJUDAN INDAH BLK J 17 TAMBAKSARI. , ...",Non RTS,Completed,AI FANG | +62-8113323196,...,https://api.ninjavan.co/assets/01db7f0d-5e0f-4...,2025-08-01 18:13:54,None,2025-08-01T18:13:54,None,1,None,2025-07-30 18:59:29,1.0,3.0
2,2025-07-30T17:05:35,IDL250730087016,10317451,PT Indotama Domestik Lestari - Reguler (Corp DS),IDCB2507003069,PT Indotama Partner Logistics - Head Office Ka...,"Jl. Pluit Putra Raya No.5 , RT 11 RW 6 , Penja...",Non RTS,Completed,(IBU LIANA) PLUIT LIFESTYLE CENTRE (SYLVIA HEN...,...,https://api.ninjavan.co/assets/f7fc58e7-64e5-4...,2025-08-01 15:07:00,None,2025-08-01T15:07:00,None,1,None,2025-07-30 18:59:29,1.0,2.0
3,2025-07-30T17:05:36,IDL250730087099,10317451,PT Indotama Domestik Lestari - Reguler (Corp DS),IDCB2507003123,PT Indotama Partner Logistics - Head Office Ka...,"JL MARTADINATA 24 , SUDIROPRAJAN , Jebres - Ko...",Non RTS,Completed,MARIA ANNA | +62-8174711796,...,https://api.ninjavan.co/assets/f6e32851-26c7-4...,2025-08-01 14:47:42,None,2025-08-01T14:47:42,None,1,None,2025-07-30 18:59:29,1.0,4.0
4,2025-07-30T17:05:37,IDL250730087079,10317451,PT Indotama Domestik Lestari - Reguler (Corp DS),IDCB2507003124,PT Indotama Partner Logistics - Head Office Ka...,"ANIVA GRANDE GA/07, GADING SERPONG, PAGEDANGAN...",Non RTS,Completed,MUTIARA | +62 838‑9894‑5434,...,https://api.ninjavan.co/assets/ff551118-b6ba-4...,2025-08-01 14:48:53,None,2025-08-01T14:48:53,None,1,None,2025-07-30 18:59:29,1.0,2.0

In [212]:
def determine_flag_sla(row):
    if row['granular_status'] == "Cancelled":
      row['actual_sla'] = pd.NaT
      row['sla_days'] = pd.NaT
      return "Cancelled"
    elif pd.isnull(row['first_attempt_at']):
        return "On Going"
    elif row['actual_sla'] <= row['sla_days']:
        return "Hit"
    else:
        return "Miss"

final_data['sla_flag'] = final_data.apply(determine_flag_sla, axis=1)

In [213]:
final_data.head()

,order_creation_datetime,tracking_id,global_shipper_id,shipper_name,shipper_reference_no,from_address,to_address,rts_flag,granular_status,to_name,...,first_attempt_at,first_fail_reason,last_attempt_at,last_fail_reason,no_of_attempt,cod_value,start_clock_datetime,actual_sla,sla_days,sla_flag
0,2025-07-30T17:05:34,IDL250730087027,10317451,PT Indotama Domestik Lestari - Reguler (Corp DS),IDCB2507003068,PT Indotama Partner Logistics - Head Office Ka...,"Jl. Pluit Putra Raya No.5 , RT 11 RW 6 , Penja...",Non RTS,Completed,(IBU LIANA) PLUIT LIFESTYLE CENTRE (LIE FEI CH...,...,2025-08-01 15:07:00,None,2025-08-01T15:07:00,None,1,None,2025-07-30 18:59:29,1.0,2.0,Hit
1,2025-07-30T17:05:34,IDL250730087030,10317451,PT Indotama Domestik Lestari - Reguler (Corp DS),IDCB2507003077,PT Indotama Partner Logistics - Head Office Ka...,"VILLA KALIJUDAN INDAH BLK J 17 TAMBAKSARI. , ...",Non RTS,Completed,AI FANG | +62-8113323196,...,2025-08-01 18:13:54,None,2025-08-01T18:13:54,None,1,None,2025-07-30 18:59:29,1.0,3.0,Hit
2,2025-07-30T17:05:35,IDL250730087016,10317451,PT Indotama Domestik Lestari - Reguler (Corp DS),IDCB2507003069,PT Indotama Partner Logistics - Head Office Ka...,"Jl. Pluit Putra Raya No.5 , RT 11 RW 6 , Penja...",Non RTS,Completed,(IBU LIANA) PLUIT LIFESTYLE CENTRE (SYLVIA HEN...,...,2025-08-01 15:07:00,None,2025-08-01T15:07:00,None,1,None,2025-07-30 18:59:29,1.0,2.0,Hit
3,2025-07-30T17:05:36,IDL250730087099,10317451,PT Indotama Domestik Lestari - Reguler (Corp DS),IDCB2507003123,PT Indotama Partner Logistics - Head Office Ka...,"JL MARTADINATA 24 , SUDIROPRAJAN , Jebres - Ko...",Non RTS,Completed,MARIA ANNA | +62-8174711796,...,2025-08-01 14:47:42,None,2025-08-01T14:47:42,None,1,None,2025-07-30 18:59:29,1.0,4.0,Hit
4,2025-07-30T17:05:37,IDL250730087079,10317451,PT Indotama Domestik Lestari - Reguler (Corp DS),IDCB2507003124,PT Indotama Partner Logistics - Head Office Ka...,"ANIVA GRANDE GA/07, GADING SERPONG, PAGEDANGAN...",Non RTS,Completed,MUTIARA | +62 838‑9894‑5434,...,2025-08-01 14:48:53,None,2025-08-01T14:48:53,None,1,None,2025-07-30 18:59:29,1.0,2.0,Hit

In [214]:
final_data.to_csv('final_check2.csv')

## Dump Data to Google Sheet

In [215]:
import gspread as gs
from gspread_dataframe import set_with_dataframe

credentials = {
  "type": "service_account",
  "project_id": "ninjavanbiid",
  "private_key_id": "8fac04201c98dfa10ec7a73f1843e2280adaa618",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC5V/nhspBOJors\nsSRmcx0CQqd87MCvcZ5cn/iPe9zjZV9Z5A71JBUG6ORtvk9Ypek/JhGmvaDZKxe4\n7dquda+0VxIEkdFW+HWk/9sAVVbGuGs3m8cg7Mgviq0EqZ4+Rve99IsGDjX1hcdo\n9f/wAzqh8H5tw/5gxjuFqcrttuaE+tKfgicEGxggNf+hO6LFU6hsFMV8yVp7AsoR\nL3I5ZLk/RMspjWAf5HGzyLbPBJpW+5tES1JazjYvu1/BA+gj9q6C6bsnagnOE6+o\n1mkTq2PNgWLKYl9WILr0woC8HdtyFJIQ4lF8M/i82u2N2cCYF/d8UfFDvsKHBAk2\ni1Cfw/T9AgMBAAECggEAQ8fPo2Fo8puXzK2PkUPhxPTZSY9PfBnB/z+lZ9u1URe+\ngiIr8ixq4CcFerjRTasHHMfwRpksnJ7swv2BLrHtOrdo6HDnLLYaV+gVkA6leHDz\nDNgUP484OmKtmXnqW/4aFca7nNBPnWV6IoFsQrr7k0NfCQdXHM8B74TDqKFttg1f\nnBKTmCNsDTRS1FsMteYolxRb1o2Yb6YdycmpCATmaWkFxH7i8fS7x2f1oGckBqB0\nS3mkOI+gkxxOLU6qH/701k9jPhrcgpI/y12PsaPG6l2fJ2KCUXiNCQEa95/4J6k9\nWGTbbPIlTdfX6ZJNbQXmYIbFXXDt0KsaBC/2J6aAJQKBgQD3sX0EY8tDhQduTuIH\n9FJlveziBn8ThwgcjFknrLKfFBKIEgLmYW3ZcofTShcayiEzAA/hn8IJlShph9+w\nUGg4Vrte22GnRhrwa+y6/2VXmKwIxn8aZrQbYHnz7HcT+qU2KQCQ41tV+qgDDZPc\n39GFvv3lssZU253Hxt8fzD+qdwKBgQC/jzMfPkc4I5bnG2gLlHxbm6gAZhezeRWX\nFBG5ZLdU3AWBW9ScMWtfGPSc4+inrrqx9/fPLEr6qRzYJg47MdRJkzjCHflA5tBg\n1xrja3MmK9V+4GA5EYgBQ9R3JDzgOtic7VZ9o0Pft5n2LpnghcqnYHPNUCcf4awa\ntpYb1LIFKwKBgH+0Ha2uufS02JDx0K2jNPxJwKEEEm6B9xeo8Kp46psD4U4QYzhe\nUSGEYCz6jRD918IQrR95m7QPGAfYyuZ/fkxVw0LzvtRcW7VLH4GF/bz89O2NUajN\n/NwEkLvHVdmSJ63V0/nfjo60rfzs+igtqTvYrdTIqGLF3AJNMWqWhtifAoGAfzMZ\noT97jz2isKe0OSxKP5Jmxo0EY/qdaYq8Ej1ct466YSGXVnhCcg1iMOPt05rlAdRE\ny18AEt5E9wqeHJSEAK8v20aIAp7B8+wiQK1S8x/cTrmza3HGvABMjyiS+9pXiCzZ\nZ+gH5ABIzf43061D2kzj2IvGzxbNb5eaqbRc2a0CgYEAuRt6xVjiboMTB49hU3KD\nh3BfJ9gFeuvK8rH2fc44HB/TOlYXvlo/7V5EVn8Bxa2TStVt9b7fzjRTcS69A9yS\n91/qkH2FBYIutT27t15cE7+I/St68MkjlnCp4k+9BWnm1IKkXMpjvJEANEZJsAQ6\n5mJ/qaajzCsmemzVFegKAlU=\n-----END PRIVATE KEY-----\n",
  "client_email": "automation@ninjavanbiid.iam.gserviceaccount.com",
  "client_id": "100326913583619321970",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/automation%40ninjavanbiid.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
gc = gs.service_account_from_dict(credentials)

def connect_to_sheet(url):
    workbook = gc.open_by_url(url)
    return workbook

def connect_to_tab(url, tab_name):
    workbook = connect_to_sheet(url)
    tab = workbook.worksheet(tab_name)
    return tab

def clean_data(url, tab_name):
    workbook = connect_to_sheet(url)
    workbook.values_clear(f'{tab_name}')
    return print('Clean Succeed, Check your Gsheet')

import json
from datetime import time

def dump_data(data, url, tab_name, init_cell):
    workbook = connect_to_sheet(url)
    data = data.values.tolist()
    workbook.values_append(f'{tab_name}!'+init_cell,
                           {'valueInputOption': 'USER_ENTERED'},
                           {'values': data})
    return print('Dumping succeed, Check your Gsheet')

In [216]:
for col in final_data.select_dtypes(include=['float64', 'datetime64', 'int64', 'object']).columns:
    final_data[col] = final_data[col].astype(str)

final_data_fix = final_data.fillna('')

url_dump = url_dump
range_delete = "Data!A2:AD40000"
clean_data(url_dump, range_delete)

url_dump = url_dump
tab_name_dump = "Data"
init_cell = "A2"
dump_data(final_data_fix, url_dump, tab_name_dump, init_cell)
print("Data Weekly IDL already dump check data in template")

Clean Succeed, Check your Gsheet
Dumping succeed, Check your Gsheet
Data Weekly IDL already dump check data in template

In [217]:
from datetime import datetime, timedelta
from zoneinfo import ZoneInfo

# --- Waktu proses sesuai WIB ---
today = datetime.now(ZoneInfo("Asia/Jakarta"))

# --- Hitung Minggu terakhir (≤ hari ini) ---
offset = (today.weekday() - 6) % 7
last_sunday = today - timedelta(days=offset)

# --- Format teks ---
start_date = datetime.strptime("2024-08-01", "%Y-%m-%d")
start_date_str = start_date.strftime("%d %B %Y")
end_date_str   = last_sunday.strftime("%d %B %Y")

title = f"Summary Weekly Report PT Indotama Domestik Lestari {start_date_str} - {end_date_str}"
updated_time = today.strftime("%d %B %Y %H:%M WIB")
updated_text = f"Updated {updated_time}"

process_time = today.strftime("%A, %d %B %Y %H:%M WIB")
process_text = f"Updated on {process_time}"

# --- Update ke Sheet ---
sheet.update("A1", [[title]])
sheet.update("A3", [[process_text]])

/tmp/ipython-input-1297687277.py:24: DeprecationWarning: The order of arguments in worksheet.update() has changed. Please pass values first and range_name secondor used named arguments (range_name=, values=)
  sheet.update("A1", [[title]])
/tmp/ipython-input-1297687277.py:25: DeprecationWarning: The order of arguments in worksheet.update() has changed. Please pass values first and range_name secondor used named arguments (range_name=, values=)
  sheet.update("A3", [[process_text]])

{'spreadsheetId': '1Ok4hXiWec0haX4Jpr90F_bhUTRhhq1NX4ExvXfAKrwc',
 'updatedRange': 'Summary!A3',
 'updatedRows': 1,
 'updatedColumns': 1,
 'updatedCells': 1}