<a href="https://colab.research.google.com/github/assyifahnurlaeli/assyifahnurlaeli/blob/Porto/Whitelab_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Daily Whitelab Reporting**

In [ ]:
# start_date and end_date
# edit start date and end date here
from datetime import datetime
start_date = '2025-04-28'
# end_date = '2025-06-13'
end_date = datetime.today().strftime('%Y-%m-%d')

# edit weekly periode here (for rename the files)
# periode = '29 Juli  - 04 Agustus 2024'
url_dump = 'https://docs.google.com/spreadsheets/d/11DIZ-4ex0f-SKLZegqs1FE4BOVgOw8bNEz2dxeAK39A/edit?pli=1&gid=1273541102#gid=1273541102'

In [ ]:
end_date

'2025-09-10'

# **Library Loading**

In [ ]:
import os
import requests
import time
# from pprint import pprint
import json
import pandas as pd
import sys
from datetime import datetime,timedelta
start_time = datetime.now()
import numpy as np
# from google.colab import drive


from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from smtplib import SMTP
import ssl
import smtplib
!pip install pretty_html_table
from pretty_html_table import build_table

# drive.mount('/drive')

def poll_job(s, redash_url, job):
    # TODO: add timeout
    while job['status'] not in (3,4):
        response = s.get('{}/api/jobs/{}'.format(redash_url, job['id']))
        job = response.json()['job']
        time.sleep(5)

    if job['status'] == 3:
        return job['query_result_id']

    return None


def get_fresh_query_result(redash_url, query_id, api_key, params):
    s = requests.Session()
    s.headers.update({'Authorization': 'Key {}'.format(api_key)})

    payload = dict(max_age=0, parameters=params)

    response = s.post('{}/api/queries/{}/results'.format(redash_url, query_id), data=json.dumps(payload))

    if response.status_code != 200:
        return 'Refresh failed'
        raise Exception('Refresh failed.')

    result_id = poll_job(s, redash_url, response.json()['job'])

    if result_id:
        while True:
            try:
                response = s.get('{}/api/queries/{}/results/{}.json'.format(redash_url, query_id, result_id))
                break
            except:
                print('retry')

        if response.status_code != 200:
            raise Exception('Failed getting results.')
    else:
        raise Exception('Query execution failed.')

    return response.json()['query_result']['data']['rows']

Collecting pretty_html_table
  Downloading pretty_html_table-0.9.16-py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from pretty_html_table) (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas->pretty_html_table) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->pretty_html_table) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->pretty_html_table) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->pretty_html_table) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->pretty_html_table) (1.17.0)
Downloading pretty_html_table-0.9.16-py3-none-any.whl (6.8 kB)
Installing collected packages: pretty_html_table
Successfully installed pretty_html_table-0.9.16

In [ ]:
# raw_data= pd.read_csv('/content/Raw Data.csv')

In [ ]:
# raw_data.columns

## **Pull Data from Redash 4791 Whitelab**

In [ ]:
print('>> Pulling data from Redash...')
loopcounter = 0
while True:
    try:
        params = {'end_forward_creation_datetime':end_date, 'start_forward_creation_datetime':start_date, 'shipper_id':'10968086'}
        api_key = 'KGy4OJdamBVI2gUWdjBfKgj8cpUETJwVqZPwb2Yf'
        result = get_fresh_query_result('https://redash-id.ninjavan.co/',4791, api_key, params)
        print('>> Pulling data SUCCESS')
        break
    except:
        print('Pulling data failed. Retrying..')
        loopcounter = loopcounter +1
        if loopcounter >=5:
            break

raw_data = pd.DataFrame(result)
print("Total Order : ",raw_data.shape[0])
# print("Number of Shipper with Order : ",raw_data['global_shipper_id'].nunique())

>> Pulling data from Redash...
>> Pulling data SUCCESS
Total Order :  234

In [ ]:
raw_data

,AWB_Resi,rdo_tracking_id,Entry_AWB,from_address2,from_l2,from_l2_id,to_l2,to_l2_id,koli,rounded,nv_weight,nama_toko,Nama_Penerima,Alamat_Penerima,PT,granular_status,TGL_Sukses_Kiriman,latest_ib_date,1st_attempt_datetime,aging_days
0,WHTLB25000374-EVENT,None,2025-08-13T17:55:33,,Kota Tangerang,ID_B00042,null,null,4,38,37.70,WHTLAB,Booth Tangerang City,"a.n Lusi Jl. Jenderal Sudirman No.1, Cikokol, ...",PT CANTIK ALAM SENTOSA,Completed,2025-08-18T14:38:15,2025-08-17T09:16:51,2025-08-18T14:38:15,24.0417
1,WHTLB25001785,None,2025-06-18T17:04:01,,Kota Tangerang,ID_B00042,null,null,2,16,16.05,WHTLAB,Ko Nico,Jl Anyelir 2 (Villa taman bandara blok F3 no 4...,PT Natura Deca Kosmetika,Completed,2025-06-20T13:46:56,2025-06-19T08:20:10,2025-06-20T13:46:56,83.0833
2,WHTLB25002263,None,2025-07-30T16:44:17,,Kota Tangerang,ID_B00042,null,null,2,18,17.80,WHTLAB,Ko Nico,Jl Anyelir 2 (Villa taman bandara blok F3 no 4...,PT NATURA DECA SEJAHTERA,Completed,2025-07-31T21:51:35,2025-07-31T00:03:25,2025-07-31T21:51:35,41.4167
3,WHTLBW25000269,None,2025-06-18T17:06:25,,Kota Tangerang,ID_B00042,Kab. Bekasi,ID_B00084,2,17,16.55,WHTLAB,Booth Lippo Cikarang,Mall Lippo Cikarang Jl MH. Thamrin Mall Lippo ...,PT Cantik Alam Sentosa,Completed,2025-06-19T16:59:52,2025-06-19T00:28:01,2025-06-19T16:59:52,83.4167
4,WHTLB25001211,None,2025-04-28T17:09:56,", Pademangan , Kota Jakarta Utara , DKI Jakarta",Kota Tangerang,ID_B00042,Kota Jakarta Utara,ID_B00068,3,15,14.75,WHTLAB,PT Aneka Kosmetindo Sejahtera,Jl sunter kemayoran no 126 sebelah sunter star...,PT SARI MELATI KENCANA TBK,Completed,2025-05-02T12:58:36,2025-05-01T22:04:30,2025-05-02T12:58:36,131.5000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,WHTLBA072025-0251,WHTLBA072025-0251-DO,2025-07-29T15:59:53,,Kota Bekasi,ID_B00096,Kab. Sumedang,ID_B00106,2,8,8.15,WHTLAB,KAKA BEAUTY JATINANGOR,"A.n Riany Jl. Raya Jatinangor No.11, Cibeusi, ...",PT NATURA DECA SEJAHTERA,Completed,2025-07-31T18:47:04,2025-07-30T17:06:20,2025-07-31T18:47:04,41.7083
230,WHTLB25000366-EVENT,None,2025-08-06T15:46:50,,Kota Tangerang,ID_B00042,Kota Surabaya,ID_B00177,1,3,3.20,WHTLAB,Booth TP TUNJUNGAN,"A.n Devia Jl. Basuki Rahmat 60261 No.8-12, Ked...",PT CANTIK ALAM SENTOSA,Completed,2025-08-08T13:40:32,2025-08-07T01:21:28,2025-08-08T13:40:32,34.3750
231,WHTLB25000301,None,2025-07-08T18:17:05,,Kota Tangerang,ID_B00042,Kota Tangerang,ID_B00042,1,8,7.48,WHTLAB,AEON ALAM SUTERA,Mall @ Alam Sutera Lt. LG Jl. Jalur Sutera Bar...,PT NATURA DECA KOSMETIKA,Completed,2025-07-17T17:18:20,2025-07-15T19:58:34,2025-07-17T17:18:20,56.5833
232,WHTLB25000264,None,2025-06-10T16:04:01,", Pademangan , Kota Jakarta Utara , DKI Jakarta",Kota Tangerang,ID_B00042,Kab. Bekasi,ID_B00084,3,32,31.35,WHTLAB,AEON DELTA MAS,"Ganesha Boulevard, Desa/Kelurahan Hegarmukti, ...",PT NATURA DECA SENTOSA,Completed,2025-06-12T22:28:08,2025-06-11T12:52:31,2025-06-12T22:28:08,90.8750
233,WHTLB25001854,WHTLB25001854-DO,2025-06-26T18:46:32,,Kota Tangerang,ID_B00042,Kota Surabaya,ID_B00177,2,23,22.84,WHTLAB,PT PASIFIK DISTRIBUSI INDONESIA,"Margomulyo No.65D, Greges, Kec. Asem Rowo, Sur...",PT Natura Deca Kosmetika,Completed,2025-07-03T14:09:40,2025-06-27T02:43:07,2025-07-03T14:09:40,75.2917

In [ ]:
import gspread as gs
from gspread_dataframe import set_with_dataframe

credentials = {
  "type": "service_account",
  "project_id": "ninjavanbiid",
  "private_key_id": "8fac04201c98dfa10ec7a73f1843e2280adaa618",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC5V/nhspBOJors\nsSRmcx0CQqd87MCvcZ5cn/iPe9zjZV9Z5A71JBUG6ORtvk9Ypek/JhGmvaDZKxe4\n7dquda+0VxIEkdFW+HWk/9sAVVbGuGs3m8cg7Mgviq0EqZ4+Rve99IsGDjX1hcdo\n9f/wAzqh8H5tw/5gxjuFqcrttuaE+tKfgicEGxggNf+hO6LFU6hsFMV8yVp7AsoR\nL3I5ZLk/RMspjWAf5HGzyLbPBJpW+5tES1JazjYvu1/BA+gj9q6C6bsnagnOE6+o\n1mkTq2PNgWLKYl9WILr0woC8HdtyFJIQ4lF8M/i82u2N2cCYF/d8UfFDvsKHBAk2\ni1Cfw/T9AgMBAAECggEAQ8fPo2Fo8puXzK2PkUPhxPTZSY9PfBnB/z+lZ9u1URe+\ngiIr8ixq4CcFerjRTasHHMfwRpksnJ7swv2BLrHtOrdo6HDnLLYaV+gVkA6leHDz\nDNgUP484OmKtmXnqW/4aFca7nNBPnWV6IoFsQrr7k0NfCQdXHM8B74TDqKFttg1f\nnBKTmCNsDTRS1FsMteYolxRb1o2Yb6YdycmpCATmaWkFxH7i8fS7x2f1oGckBqB0\nS3mkOI+gkxxOLU6qH/701k9jPhrcgpI/y12PsaPG6l2fJ2KCUXiNCQEa95/4J6k9\nWGTbbPIlTdfX6ZJNbQXmYIbFXXDt0KsaBC/2J6aAJQKBgQD3sX0EY8tDhQduTuIH\n9FJlveziBn8ThwgcjFknrLKfFBKIEgLmYW3ZcofTShcayiEzAA/hn8IJlShph9+w\nUGg4Vrte22GnRhrwa+y6/2VXmKwIxn8aZrQbYHnz7HcT+qU2KQCQ41tV+qgDDZPc\n39GFvv3lssZU253Hxt8fzD+qdwKBgQC/jzMfPkc4I5bnG2gLlHxbm6gAZhezeRWX\nFBG5ZLdU3AWBW9ScMWtfGPSc4+inrrqx9/fPLEr6qRzYJg47MdRJkzjCHflA5tBg\n1xrja3MmK9V+4GA5EYgBQ9R3JDzgOtic7VZ9o0Pft5n2LpnghcqnYHPNUCcf4awa\ntpYb1LIFKwKBgH+0Ha2uufS02JDx0K2jNPxJwKEEEm6B9xeo8Kp46psD4U4QYzhe\nUSGEYCz6jRD918IQrR95m7QPGAfYyuZ/fkxVw0LzvtRcW7VLH4GF/bz89O2NUajN\n/NwEkLvHVdmSJ63V0/nfjo60rfzs+igtqTvYrdTIqGLF3AJNMWqWhtifAoGAfzMZ\noT97jz2isKe0OSxKP5Jmxo0EY/qdaYq8Ej1ct466YSGXVnhCcg1iMOPt05rlAdRE\ny18AEt5E9wqeHJSEAK8v20aIAp7B8+wiQK1S8x/cTrmza3HGvABMjyiS+9pXiCzZ\nZ+gH5ABIzf43061D2kzj2IvGzxbNb5eaqbRc2a0CgYEAuRt6xVjiboMTB49hU3KD\nh3BfJ9gFeuvK8rH2fc44HB/TOlYXvlo/7V5EVn8Bxa2TStVt9b7fzjRTcS69A9yS\n91/qkH2FBYIutT27t15cE7+I/St68MkjlnCp4k+9BWnm1IKkXMpjvJEANEZJsAQ6\n5mJ/qaajzCsmemzVFegKAlU=\n-----END PRIVATE KEY-----\n",
  "client_email": "automation@ninjavanbiid.iam.gserviceaccount.com",
  "client_id": "100326913583619321970",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/automation%40ninjavanbiid.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
gc = gs.service_account_from_dict(credentials)

def connect_to_sheet(url):
    workbook = gc.open_by_url(url)
    return workbook

def connect_to_tab(url, tab_name):
    workbook = connect_to_sheet(url)
    tab = workbook.worksheet(tab_name)
    return tab

def clean_data(url, tab_name):
    workbook = connect_to_sheet(url)
    workbook.values_clear(f'{tab_name}')
    return print('Clean Succeed, Check your Gsheet')

import json
from datetime import time

def dump_data(data, url, tab_name, init_cell):
    workbook = connect_to_sheet(url)
    data = data.values.tolist()
    workbook.values_append(f'{tab_name}!'+init_cell,
                           {'valueInputOption': 'USER_ENTERED'},
                           {'values': data})
    return print('Dumping succeed, Check your Gsheet')

## **Tarik Data SLA dari Google Sheet Rate Card**

In [ ]:
ws = gc.open_by_url('https://docs.google.com/spreadsheets/d/11DIZ-4ex0f-SKLZegqs1FE4BOVgOw8bNEz2dxeAK39A/edit?pli=1&gid=1931386894#gid=1931386894').worksheet('Copy of SLA')

# Get All values from google sheet
values = ws.get_all_values()

# Create dataframe using value
df_raw = pd.DataFrame(values)

# Name cell in A1 as 'Origin' as header for column A
header = ['Origin'] + df_raw.iloc[0, 1:].tolist()
df_sla_pivot = df_raw.iloc[1:].reset_index(drop=True)
df_sla_pivot.columns = header

# Convert from wide form to long form
df_sla_long = df_sla_pivot.melt(id_vars=['Origin'], var_name='Destination', value_name='SLA_Days')

# Get only maximum day from SLA days value (from 1-2 only get 2)
df_sla_long['SLA_Days'] = df_sla_long['SLA_Days'].str.split('-').str[-1]
df_sla_long['SLA_Days'] = pd.to_numeric(df_sla_long['SLA_Days'], errors='coerce')

# Clean Origin Id from data raw to format needed (from ID_B00001_1 to ID_B00001) clean suffix
df_sla_long['Origin'] = df_sla_long['Origin'].str.extract(r'^(ID_B\d+)')

# Print SLA Days after Fixing SLA Days
print("Tarik SLA Days dan ubah format SLA Days Done")
df_sla_long.head()

Tarik SLA Days dan ubah format SLA Days Done

      Origin Destination  SLA_Days
0  ID_B00001   ID_B00001         3
1  ID_B00001   ID_B00001         3
2  ID_B00001   ID_B00001         3
3  ID_B00001   ID_B00001         3
4  ID_B00001   ID_B00001         3

In [ ]:
df_sla_long = df_sla_long.drop_duplicates(subset=['Origin', 'Destination'])

## **Merging Raw Data Redash with SLA Days**

In [ ]:
df_merged = raw_data.merge(df_sla_long, left_on=['from_l2_id', 'to_l2_id'], right_on=['Origin', 'Destination'], how='left')
df_merged = df_merged.drop(['Origin', 'Destination'], axis=1)

df_merged.head()

,AWB_Resi,rdo_tracking_id,Entry_AWB,from_address2,from_l2,from_l2_id,to_l2,to_l2_id,koli,rounded,...,nama_toko,Nama_Penerima,Alamat_Penerima,PT,granular_status,TGL_Sukses_Kiriman,latest_ib_date,1st_attempt_datetime,aging_days,SLA_Days
0,WHTLB25000374-EVENT,None,2025-08-13T17:55:33,,Kota Tangerang,ID_B00042,null,null,4,38,...,WHTLAB,Booth Tangerang City,"a.n Lusi Jl. Jenderal Sudirman No.1, Cikokol, ...",PT CANTIK ALAM SENTOSA,Completed,2025-08-18T14:38:15,2025-08-17T09:16:51,2025-08-18T14:38:15,24.0417,NaN
1,WHTLB25001785,None,2025-06-18T17:04:01,,Kota Tangerang,ID_B00042,null,null,2,16,...,WHTLAB,Ko Nico,Jl Anyelir 2 (Villa taman bandara blok F3 no 4...,PT Natura Deca Kosmetika,Completed,2025-06-20T13:46:56,2025-06-19T08:20:10,2025-06-20T13:46:56,83.0833,NaN
2,WHTLB25002263,None,2025-07-30T16:44:17,,Kota Tangerang,ID_B00042,null,null,2,18,...,WHTLAB,Ko Nico,Jl Anyelir 2 (Villa taman bandara blok F3 no 4...,PT NATURA DECA SEJAHTERA,Completed,2025-07-31T21:51:35,2025-07-31T00:03:25,2025-07-31T21:51:35,41.4167,NaN
3,WHTLBW25000269,None,2025-06-18T17:06:25,,Kota Tangerang,ID_B00042,Kab. Bekasi,ID_B00084,2,17,...,WHTLAB,Booth Lippo Cikarang,Mall Lippo Cikarang Jl MH. Thamrin Mall Lippo ...,PT Cantik Alam Sentosa,Completed,2025-06-19T16:59:52,2025-06-19T00:28:01,2025-06-19T16:59:52,83.4167,2.0
4,WHTLB25001211,None,2025-04-28T17:09:56,", Pademangan , Kota Jakarta Utara , DKI Jakarta",Kota Tangerang,ID_B00042,Kota Jakarta Utara,ID_B00068,3,15,...,WHTLAB,PT Aneka Kosmetindo Sejahtera,Jl sunter kemayoran no 126 sebelah sunter star...,PT SARI MELATI KENCANA TBK,Completed,2025-05-02T12:58:36,2025-05-01T22:04:30,2025-05-02T12:58:36,131.5000,2.0

In [ ]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 234 entries, 0 to 233
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   AWB_Resi              234 non-null    object
 1   rdo_tracking_id       28 non-null     object
 2   Entry_AWB             234 non-null    object
 3   from_address2         234 non-null    object
 4   from_l2               216 non-null    object
 5   from_l2_id            216 non-null    object
 6   to_l2                 216 non-null    object
 7   to_l2_id              216 non-null    object
 8   koli                  234 non-null    int64
 9   rounded               234 non-null    int64
 10  nv_weight             234 non-null    float64
 11  nama_toko             234 non-null    object
 12  Nama_Penerima         234 non-null    object
 13  Alamat_Penerima       234 non-null    object
 14  PT                    234 non-null    object
 15  granular_status       234 non-null    object
 16  TGL_Sukses_Kiriman    212 non-null    object
 17  latest_ib_date        216 non-null    object
 18  1st_attempt_datetime  212 non-null    object
 19  aging_days            234 non-null    float64
 20  SLA_Days              197 non-null    float64
dtypes: float64(3), int64(2), object(16)
memory usage: 38.5+ KB

In [ ]:
import pandas as pd
from datetime import datetime

import pandas as pd

def parse_multiple_date_formats(date_str):
    # Coba format dengan 'T' dulu
    try:
        return pd.to_datetime(date_str, format='%Y-%m-%dT%H:%M:%S')
    except:
        pass
    # Coba format lain (tanpa 'T', misal pakai spasi)
    try:
        return pd.to_datetime(date_str, format='%Y-%m-%d %H:%M:%S')
    except:
        pass
    # Jika semua gagal, kembalikan NaT
    return pd.NaT

# Terapkan ke kolom dataframe
df_merged['TGL_Sukses_Kiriman'] = df_merged['TGL_Sukses_Kiriman'].apply(parse_multiple_date_formats)
df_merged['latest_ib_date'] = df_merged['latest_ib_date'].apply(parse_multiple_date_formats)
df_merged['SLA_Days'] = pd.to_numeric(df_merged['SLA_Days'], errors='coerce')

In [ ]:
df_merged

,AWB_Resi,rdo_tracking_id,Entry_AWB,from_address2,from_l2,from_l2_id,to_l2,to_l2_id,koli,rounded,...,nama_toko,Nama_Penerima,Alamat_Penerima,PT,granular_status,TGL_Sukses_Kiriman,latest_ib_date,1st_attempt_datetime,aging_days,SLA_Days
0,WHTLB25000374-EVENT,None,2025-08-13T17:55:33,,Kota Tangerang,ID_B00042,null,null,4,38,...,WHTLAB,Booth Tangerang City,"a.n Lusi Jl. Jenderal Sudirman No.1, Cikokol, ...",PT CANTIK ALAM SENTOSA,Completed,2025-08-18 14:38:15,2025-08-17 09:16:51,2025-08-18T14:38:15,24.0417,NaN
1,WHTLB25001785,None,2025-06-18T17:04:01,,Kota Tangerang,ID_B00042,null,null,2,16,...,WHTLAB,Ko Nico,Jl Anyelir 2 (Villa taman bandara blok F3 no 4...,PT Natura Deca Kosmetika,Completed,2025-06-20 13:46:56,2025-06-19 08:20:10,2025-06-20T13:46:56,83.0833,NaN
2,WHTLB25002263,None,2025-07-30T16:44:17,,Kota Tangerang,ID_B00042,null,null,2,18,...,WHTLAB,Ko Nico,Jl Anyelir 2 (Villa taman bandara blok F3 no 4...,PT NATURA DECA SEJAHTERA,Completed,2025-07-31 21:51:35,2025-07-31 00:03:25,2025-07-31T21:51:35,41.4167,NaN
3,WHTLBW25000269,None,2025-06-18T17:06:25,,Kota Tangerang,ID_B00042,Kab. Bekasi,ID_B00084,2,17,...,WHTLAB,Booth Lippo Cikarang,Mall Lippo Cikarang Jl MH. Thamrin Mall Lippo ...,PT Cantik Alam Sentosa,Completed,2025-06-19 16:59:52,2025-06-19 00:28:01,2025-06-19T16:59:52,83.4167,2.0
4,WHTLB25001211,None,2025-04-28T17:09:56,", Pademangan , Kota Jakarta Utara , DKI Jakarta",Kota Tangerang,ID_B00042,Kota Jakarta Utara,ID_B00068,3,15,...,WHTLAB,PT Aneka Kosmetindo Sejahtera,Jl sunter kemayoran no 126 sebelah sunter star...,PT SARI MELATI KENCANA TBK,Completed,2025-05-02 12:58:36,2025-05-01 22:04:30,2025-05-02T12:58:36,131.5000,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,WHTLBA072025-0251,WHTLBA072025-0251-DO,2025-07-29T15:59:53,,Kota Bekasi,ID_B00096,Kab. Sumedang,ID_B00106,2,8,...,WHTLAB,KAKA BEAUTY JATINANGOR,"A.n Riany Jl. Raya Jatinangor No.11, Cibeusi, ...",PT NATURA DECA SEJAHTERA,Completed,2025-07-31 18:47:04,2025-07-30 17:06:20,2025-07-31T18:47:04,41.7083,2.0
230,WHTLB25000366-EVENT,None,2025-08-06T15:46:50,,Kota Tangerang,ID_B00042,Kota Surabaya,ID_B00177,1,3,...,WHTLAB,Booth TP TUNJUNGAN,"A.n Devia Jl. Basuki Rahmat 60261 No.8-12, Ked...",PT CANTIK ALAM SENTOSA,Completed,2025-08-08 13:40:32,2025-08-07 01:21:28,2025-08-08T13:40:32,34.3750,3.0
231,WHTLB25000301,None,2025-07-08T18:17:05,,Kota Tangerang,ID_B00042,Kota Tangerang,ID_B00042,1,8,...,WHTLAB,AEON ALAM SUTERA,Mall @ Alam Sutera Lt. LG Jl. Jalur Sutera Bar...,PT NATURA DECA KOSMETIKA,Completed,2025-07-17 17:18:20,2025-07-15 19:58:34,2025-07-17T17:18:20,56.5833,2.0
232,WHTLB25000264,None,2025-06-10T16:04:01,", Pademangan , Kota Jakarta Utara , DKI Jakarta",Kota Tangerang,ID_B00042,Kab. Bekasi,ID_B00084,3,32,...,WHTLAB,AEON DELTA MAS,"Ganesha Boulevard, Desa/Kelurahan Hegarmukti, ...",PT NATURA DECA SENTOSA,Completed,2025-06-12 22:28:08,2025-06-11 12:52:31,2025-06-12T22:28:08,90.8750,2.0
233,WHTLB25001854,WHTLB25001854-DO,2025-06-26T18:46:32,,Kota Tangerang,ID_B00042,Kota Surabaya,ID_B00177,2,23,...,WHTLAB,PT PASIFIK DISTRIBUSI INDONESIA,"Margomulyo No.65D, Greges, Kec. Asem Rowo, Sur...",PT Natura Deca Kosmetika,Completed,2025-07-03 14:09:40,2025-06-27 02:43:07,2025-07-03T14:09:40,75.2917,3.0

In [ ]:
def calculate_aging(row):
    if pd.isna(row['latest_ib_date']):  # Cek jika latest_ib_date kosong
        return None
    if row['granular_status'] == 'Completed':
        start_date = row['latest_ib_date'].date()
        end_date = row['TGL_Sukses_Kiriman'].date()
    else:
        start_date = row['latest_ib_date'].date()
        end_date = pd.Timestamp.now().date()
    return (end_date - start_date).days

# Hitung aging days
df_merged['aging_days'] = df_merged.apply(calculate_aging, axis=1)

# Tentukan verdict, hanya untuk yang aging valid dan SLA valid
df_merged['verdict'] = df_merged.apply(
    lambda row: 'MISS' if pd.notnull(row['aging_days']) and pd.notnull(row['SLA_Days']) and row['aging_days'] > row['SLA_Days']
    else '',
    axis=1
)

# Optional: Filter hanya yang MISS
df_miss_only = df_merged[df_merged['verdict'] == 'MISS']

# Tampilkan hasil
print(df_miss_only[['granular_status', 'latest_ib_date', 'TGL_Sukses_Kiriman', 'aging_days', 'SLA_Days', 'verdict']])

    granular_status      latest_ib_date  TGL_Sukses_Kiriman  aging_days  \
13        Completed 2025-08-17 03:09:25 2025-08-27 10:16:33        10.0
21        Completed 2025-07-11 06:04:10 2025-07-15 21:25:27         4.0
26        Completed 2025-06-27 02:36:11 2025-07-03 14:09:40         6.0
54        Completed 2025-07-18 23:40:31 2025-07-21 15:06:08         3.0
65        Completed 2025-06-19 00:32:35 2025-06-28 16:17:49         9.0
69        Completed 2025-06-27 02:47:54 2025-07-03 14:09:40         6.0
72        Completed 2025-07-30 01:12:43 2025-08-06 18:58:21         7.0
80        Completed 2025-07-11 06:09:11 2025-07-15 21:25:27         4.0
84        Completed 2025-06-11 23:14:25 2025-06-20 11:53:47         9.0
91        Completed 2025-07-11 06:26:10 2025-07-17 13:22:14         6.0
97        Completed 2025-06-10 02:44:40 2025-06-16 12:12:38         6.0
107       Completed 2025-06-27 01:32:58 2025-06-30 17:14:56         3.0
119       Completed 2025-06-25 02:23:47 2025-07-06 14:38:03        11.0
121       Completed 2025-08-28 01:40:54 2025-09-05 09:27:40         8.0
125       Completed 2025-06-12 06:54:05 2025-06-20 09:13:03         8.0
163       Completed 2025-07-30 01:10:37 2025-08-06 18:58:21         7.0
181       Completed 2025-06-11 23:16:23 2025-06-14 15:05:49         3.0
184       Completed 2025-07-17 00:47:19 2025-07-25 12:57:27         8.0
187       Completed 2025-07-30 01:09:22 2025-08-06 18:58:21         7.0
195       Completed 2025-07-31 23:03:14 2025-08-12 08:55:47        12.0
204       Completed 2025-08-09 00:50:31 2025-08-13 23:00:25         4.0
223       Completed 2025-07-03 18:08:56 2025-07-11 16:22:13         8.0
227       Completed 2025-06-06 20:56:18 2025-06-09 16:42:04         3.0
233       Completed 2025-06-27 02:43:07 2025-07-03 14:09:40         6.0

     SLA_Days verdict
13        7.0    MISS
21        3.0    MISS
26        3.0    MISS
54        2.0    MISS
65        7.0    MISS
69        3.0    MISS
72        3.0    MISS
80        3.0    MISS
84        4.0    MISS
91        3.0    MISS
97        4.0    MISS
107       2.0    MISS
119       7.0    MISS
121       7.0    MISS
125       7.0    MISS
163       3.0    MISS
181       2.0    MISS
184       7.0    MISS
187       3.0    MISS
195       7.0    MISS
204       3.0    MISS
223       4.0    MISS
227       2.0    MISS
233       3.0    MISS

In [ ]:
df_merged.tail()

,AWB_Resi,rdo_tracking_id,Entry_AWB,from_address2,from_l2,from_l2_id,to_l2,to_l2_id,koli,rounded,...,Nama_Penerima,Alamat_Penerima,PT,granular_status,TGL_Sukses_Kiriman,latest_ib_date,1st_attempt_datetime,aging_days,SLA_Days,verdict
229,WHTLBA072025-0251,WHTLBA072025-0251-DO,2025-07-29T15:59:53,,Kota Bekasi,ID_B00096,Kab. Sumedang,ID_B00106,2,8,...,KAKA BEAUTY JATINANGOR,"A.n Riany Jl. Raya Jatinangor No.11, Cibeusi, ...",PT NATURA DECA SEJAHTERA,Completed,2025-07-31 18:47:04,2025-07-30 17:06:20,2025-07-31T18:47:04,1.0,2.0,
230,WHTLB25000366-EVENT,None,2025-08-06T15:46:50,,Kota Tangerang,ID_B00042,Kota Surabaya,ID_B00177,1,3,...,Booth TP TUNJUNGAN,"A.n Devia Jl. Basuki Rahmat 60261 No.8-12, Ked...",PT CANTIK ALAM SENTOSA,Completed,2025-08-08 13:40:32,2025-08-07 01:21:28,2025-08-08T13:40:32,1.0,3.0,
231,WHTLB25000301,None,2025-07-08T18:17:05,,Kota Tangerang,ID_B00042,Kota Tangerang,ID_B00042,1,8,...,AEON ALAM SUTERA,Mall @ Alam Sutera Lt. LG Jl. Jalur Sutera Bar...,PT NATURA DECA KOSMETIKA,Completed,2025-07-17 17:18:20,2025-07-15 19:58:34,2025-07-17T17:18:20,2.0,2.0,
232,WHTLB25000264,None,2025-06-10T16:04:01,", Pademangan , Kota Jakarta Utara , DKI Jakarta",Kota Tangerang,ID_B00042,Kab. Bekasi,ID_B00084,3,32,...,AEON DELTA MAS,"Ganesha Boulevard, Desa/Kelurahan Hegarmukti, ...",PT NATURA DECA SENTOSA,Completed,2025-06-12 22:28:08,2025-06-11 12:52:31,2025-06-12T22:28:08,1.0,2.0,
233,WHTLB25001854,WHTLB25001854-DO,2025-06-26T18:46:32,,Kota Tangerang,ID_B00042,Kota Surabaya,ID_B00177,2,23,...,PT PASIFIK DISTRIBUSI INDONESIA,"Margomulyo No.65D, Greges, Kec. Asem Rowo, Sur...",PT Natura Deca Kosmetika,Completed,2025-07-03 14:09:40,2025-06-27 02:43:07,2025-07-03T14:09:40,6.0,3.0,MISS

In [ ]:
def calculate_aging(row):
    # Cek kalau latest_ib_date-nya valid
    if pd.isnull(row['latest_ib_date']):
        return None

    start_date = row['latest_ib_date'].date()

    if row['granular_status'] == 'Completed':
        if pd.isnull(row['TGL_Sukses_Kiriman']):
            return None
        end_date = row['TGL_Sukses_Kiriman'].date()
    else:
        end_date = pd.Timestamp.now().date()

    return (end_date - start_date).days

# Hitung aging days
df_merged['aging_days'] = df_merged.apply(calculate_aging, axis=1)

# Tentukan verdict
df_merged['verdict'] = df_merged.apply(
    lambda row: 'MISS' if pd.notnull(row['aging_days']) and pd.notnull(row['SLA_Days']) and row['aging_days'] > row['SLA_Days']
    else '',
    axis=1
)

# Filter hanya yang MISS
df_miss_only = df_merged[df_merged['verdict'] == 'MISS']

# Tampilkan hasil
print(df_miss_only[['granular_status', 'latest_ib_date', 'TGL_Sukses_Kiriman', 'aging_days', 'SLA_Days', 'verdict']])

    granular_status      latest_ib_date  TGL_Sukses_Kiriman  aging_days  \
13        Completed 2025-08-17 03:09:25 2025-08-27 10:16:33        10.0
21        Completed 2025-07-11 06:04:10 2025-07-15 21:25:27         4.0
26        Completed 2025-06-27 02:36:11 2025-07-03 14:09:40         6.0
54        Completed 2025-07-18 23:40:31 2025-07-21 15:06:08         3.0
65        Completed 2025-06-19 00:32:35 2025-06-28 16:17:49         9.0
69        Completed 2025-06-27 02:47:54 2025-07-03 14:09:40         6.0
72        Completed 2025-07-30 01:12:43 2025-08-06 18:58:21         7.0
80        Completed 2025-07-11 06:09:11 2025-07-15 21:25:27         4.0
84        Completed 2025-06-11 23:14:25 2025-06-20 11:53:47         9.0
91        Completed 2025-07-11 06:26:10 2025-07-17 13:22:14         6.0
97        Completed 2025-06-10 02:44:40 2025-06-16 12:12:38         6.0
107       Completed 2025-06-27 01:32:58 2025-06-30 17:14:56         3.0
119       Completed 2025-06-25 02:23:47 2025-07-06 14:38:03        11.0
121       Completed 2025-08-28 01:40:54 2025-09-05 09:27:40         8.0
125       Completed 2025-06-12 06:54:05 2025-06-20 09:13:03         8.0
163       Completed 2025-07-30 01:10:37 2025-08-06 18:58:21         7.0
181       Completed 2025-06-11 23:16:23 2025-06-14 15:05:49         3.0
184       Completed 2025-07-17 00:47:19 2025-07-25 12:57:27         8.0
187       Completed 2025-07-30 01:09:22 2025-08-06 18:58:21         7.0
195       Completed 2025-07-31 23:03:14 2025-08-12 08:55:47        12.0
204       Completed 2025-08-09 00:50:31 2025-08-13 23:00:25         4.0
223       Completed 2025-07-03 18:08:56 2025-07-11 16:22:13         8.0
227       Completed 2025-06-06 20:56:18 2025-06-09 16:42:04         3.0
233       Completed 2025-06-27 02:43:07 2025-07-03 14:09:40         6.0

     SLA_Days verdict
13        7.0    MISS
21        3.0    MISS
26        3.0    MISS
54        2.0    MISS
65        7.0    MISS
69        3.0    MISS
72        3.0    MISS
80        3.0    MISS
84        4.0    MISS
91        3.0    MISS
97        4.0    MISS
107       2.0    MISS
119       7.0    MISS
121       7.0    MISS
125       7.0    MISS
163       3.0    MISS
181       2.0    MISS
184       7.0    MISS
187       3.0    MISS
195       7.0    MISS
204       3.0    MISS
223       4.0    MISS
227       2.0    MISS
233       3.0    MISS

In [ ]:
df_merged

,AWB_Resi,rdo_tracking_id,Entry_AWB,from_address2,from_l2,from_l2_id,to_l2,to_l2_id,koli,rounded,...,Nama_Penerima,Alamat_Penerima,PT,granular_status,TGL_Sukses_Kiriman,latest_ib_date,1st_attempt_datetime,aging_days,SLA_Days,verdict
0,WHTLB25000374-EVENT,None,2025-08-13T17:55:33,,Kota Tangerang,ID_B00042,null,null,4,38,...,Booth Tangerang City,"a.n Lusi Jl. Jenderal Sudirman No.1, Cikokol, ...",PT CANTIK ALAM SENTOSA,Completed,2025-08-18 14:38:15,2025-08-17 09:16:51,2025-08-18T14:38:15,1.0,NaN,
1,WHTLB25001785,None,2025-06-18T17:04:01,,Kota Tangerang,ID_B00042,null,null,2,16,...,Ko Nico,Jl Anyelir 2 (Villa taman bandara blok F3 no 4...,PT Natura Deca Kosmetika,Completed,2025-06-20 13:46:56,2025-06-19 08:20:10,2025-06-20T13:46:56,1.0,NaN,
2,WHTLB25002263,None,2025-07-30T16:44:17,,Kota Tangerang,ID_B00042,null,null,2,18,...,Ko Nico,Jl Anyelir 2 (Villa taman bandara blok F3 no 4...,PT NATURA DECA SEJAHTERA,Completed,2025-07-31 21:51:35,2025-07-31 00:03:25,2025-07-31T21:51:35,0.0,NaN,
3,WHTLBW25000269,None,2025-06-18T17:06:25,,Kota Tangerang,ID_B00042,Kab. Bekasi,ID_B00084,2,17,...,Booth Lippo Cikarang,Mall Lippo Cikarang Jl MH. Thamrin Mall Lippo ...,PT Cantik Alam Sentosa,Completed,2025-06-19 16:59:52,2025-06-19 00:28:01,2025-06-19T16:59:52,0.0,2.0,
4,WHTLB25001211,None,2025-04-28T17:09:56,", Pademangan , Kota Jakarta Utara , DKI Jakarta",Kota Tangerang,ID_B00042,Kota Jakarta Utara,ID_B00068,3,15,...,PT Aneka Kosmetindo Sejahtera,Jl sunter kemayoran no 126 sebelah sunter star...,PT SARI MELATI KENCANA TBK,Completed,2025-05-02 12:58:36,2025-05-01 22:04:30,2025-05-02T12:58:36,1.0,2.0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,WHTLBA072025-0251,WHTLBA072025-0251-DO,2025-07-29T15:59:53,,Kota Bekasi,ID_B00096,Kab. Sumedang,ID_B00106,2,8,...,KAKA BEAUTY JATINANGOR,"A.n Riany Jl. Raya Jatinangor No.11, Cibeusi, ...",PT NATURA DECA SEJAHTERA,Completed,2025-07-31 18:47:04,2025-07-30 17:06:20,2025-07-31T18:47:04,1.0,2.0,
230,WHTLB25000366-EVENT,None,2025-08-06T15:46:50,,Kota Tangerang,ID_B00042,Kota Surabaya,ID_B00177,1,3,...,Booth TP TUNJUNGAN,"A.n Devia Jl. Basuki Rahmat 60261 No.8-12, Ked...",PT CANTIK ALAM SENTOSA,Completed,2025-08-08 13:40:32,2025-08-07 01:21:28,2025-08-08T13:40:32,1.0,3.0,
231,WHTLB25000301,None,2025-07-08T18:17:05,,Kota Tangerang,ID_B00042,Kota Tangerang,ID_B00042,1,8,...,AEON ALAM SUTERA,Mall @ Alam Sutera Lt. LG Jl. Jalur Sutera Bar...,PT NATURA DECA KOSMETIKA,Completed,2025-07-17 17:18:20,2025-07-15 19:58:34,2025-07-17T17:18:20,2.0,2.0,
232,WHTLB25000264,None,2025-06-10T16:04:01,", Pademangan , Kota Jakarta Utara , DKI Jakarta",Kota Tangerang,ID_B00042,Kab. Bekasi,ID_B00084,3,32,...,AEON DELTA MAS,"Ganesha Boulevard, Desa/Kelurahan Hegarmukti, ...",PT NATURA DECA SENTOSA,Completed,2025-06-12 22:28:08,2025-06-11 12:52:31,2025-06-12T22:28:08,1.0,2.0,
233,WHTLB25001854,WHTLB25001854-DO,2025-06-26T18:46:32,,Kota Tangerang,ID_B00042,Kota Surabaya,ID_B00177,2,23,...,PT PASIFIK DISTRIBUSI INDONESIA,"Margomulyo No.65D, Greges, Kec. Asem Rowo, Sur...",PT Natura Deca Kosmetika,Completed,2025-07-03 14:09:40,2025-06-27 02:43:07,2025-07-03T14:09:40,6.0,3.0,MISS

In [ ]:
df_merged.columns

Index(['AWB_Resi', 'rdo_tracking_id', 'Entry_AWB', 'from_address2', 'from_l2',
       'from_l2_id', 'to_l2', 'to_l2_id', 'koli', 'rounded', 'nv_weight',
       'nama_toko', 'Nama_Penerima', 'Alamat_Penerima', 'PT',
       'granular_status', 'TGL_Sukses_Kiriman', 'latest_ib_date',
       '1st_attempt_datetime', 'aging_days', 'SLA_Days', 'verdict'],
      dtype='object')

In [ ]:
# Daftar urutan kolom yang kamu inginkan
new_order = [
    'AWB_Resi', 'rdo_tracking_id', 'Entry_AWB', 'from_address2',
    'to_l2', 'koli', 'rounded', 'nv_weight', 'nama_toko',
    'Nama_Penerima', 'Alamat_Penerima', 'PT', 'granular_status',
    'latest_ib_date', 'TGL_Sukses_Kiriman','SLA_Days', 'aging_days', 'verdict'
]

# Urutkan kolom sesuai new_order, lalu tampilkan
df_merged = df_merged[new_order]

In [ ]:
df_merged.columns

Index(['AWB_Resi', 'rdo_tracking_id', 'Entry_AWB', 'from_address2', 'to_l2',
       'koli', 'rounded', 'nv_weight', 'nama_toko', 'Nama_Penerima',
       'Alamat_Penerima', 'PT', 'granular_status', 'latest_ib_date',
       'TGL_Sukses_Kiriman', 'SLA_Days', 'aging_days', 'verdict'],
      dtype='object')

In [ ]:
df_merged['TGL_Sukses_Kiriman'] = df_merged['TGL_Sukses_Kiriman'].dt.strftime('%Y-%m-%d %H:%M:%S')

/tmp/ipython-input-2183114743.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_merged['TGL_Sukses_Kiriman'] = df_merged['TGL_Sukses_Kiriman'].dt.strftime('%Y-%m-%d %H:%M:%S')

In [ ]:
def ambil_kota_kabupaten(alamat):
    parts = [x.strip() for x in alamat.split(',') if x.strip()]
    return parts[-2] if len(parts) >= 2 else None

# Terapkan ke kolom address
df_merged['from_address2'] = df_merged['from_address2'].apply(ambil_kota_kabupaten)

/tmp/ipython-input-3913498274.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_merged['from_address2'] = df_merged['from_address2'].apply(ambil_kota_kabupaten)

In [ ]:
df_merged

,AWB_Resi,rdo_tracking_id,Entry_AWB,from_address2,to_l2,koli,rounded,nv_weight,nama_toko,Nama_Penerima,Alamat_Penerima,PT,granular_status,latest_ib_date,TGL_Sukses_Kiriman,SLA_Days,aging_days,verdict
0,WHTLB25000374-EVENT,None,2025-08-13T17:55:33,None,null,4,38,37.70,WHTLAB,Booth Tangerang City,"a.n Lusi Jl. Jenderal Sudirman No.1, Cikokol, ...",PT CANTIK ALAM SENTOSA,Completed,2025-08-17 09:16:51,2025-08-18 14:38:15,NaN,1.0,
1,WHTLB25001785,None,2025-06-18T17:04:01,None,null,2,16,16.05,WHTLAB,Ko Nico,Jl Anyelir 2 (Villa taman bandara blok F3 no 4...,PT Natura Deca Kosmetika,Completed,2025-06-19 08:20:10,2025-06-20 13:46:56,NaN,1.0,
2,WHTLB25002263,None,2025-07-30T16:44:17,None,null,2,18,17.80,WHTLAB,Ko Nico,Jl Anyelir 2 (Villa taman bandara blok F3 no 4...,PT NATURA DECA SEJAHTERA,Completed,2025-07-31 00:03:25,2025-07-31 21:51:35,NaN,0.0,
3,WHTLBW25000269,None,2025-06-18T17:06:25,None,Kab. Bekasi,2,17,16.55,WHTLAB,Booth Lippo Cikarang,Mall Lippo Cikarang Jl MH. Thamrin Mall Lippo ...,PT Cantik Alam Sentosa,Completed,2025-06-19 00:28:01,2025-06-19 16:59:52,2.0,0.0,
4,WHTLB25001211,None,2025-04-28T17:09:56,Kota Jakarta Utara,Kota Jakarta Utara,3,15,14.75,WHTLAB,PT Aneka Kosmetindo Sejahtera,Jl sunter kemayoran no 126 sebelah sunter star...,PT SARI MELATI KENCANA TBK,Completed,2025-05-01 22:04:30,2025-05-02 12:58:36,2.0,1.0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,WHTLBA072025-0251,WHTLBA072025-0251-DO,2025-07-29T15:59:53,None,Kab. Sumedang,2,8,8.15,WHTLAB,KAKA BEAUTY JATINANGOR,"A.n Riany Jl. Raya Jatinangor No.11, Cibeusi, ...",PT NATURA DECA SEJAHTERA,Completed,2025-07-30 17:06:20,2025-07-31 18:47:04,2.0,1.0,
230,WHTLB25000366-EVENT,None,2025-08-06T15:46:50,None,Kota Surabaya,1,3,3.20,WHTLAB,Booth TP TUNJUNGAN,"A.n Devia Jl. Basuki Rahmat 60261 No.8-12, Ked...",PT CANTIK ALAM SENTOSA,Completed,2025-08-07 01:21:28,2025-08-08 13:40:32,3.0,1.0,
231,WHTLB25000301,None,2025-07-08T18:17:05,None,Kota Tangerang,1,8,7.48,WHTLAB,AEON ALAM SUTERA,Mall @ Alam Sutera Lt. LG Jl. Jalur Sutera Bar...,PT NATURA DECA KOSMETIKA,Completed,2025-07-15 19:58:34,2025-07-17 17:18:20,2.0,2.0,
232,WHTLB25000264,None,2025-06-10T16:04:01,Kota Jakarta Utara,Kab. Bekasi,3,32,31.35,WHTLAB,AEON DELTA MAS,"Ganesha Boulevard, Desa/Kelurahan Hegarmukti, ...",PT NATURA DECA SENTOSA,Completed,2025-06-11 12:52:31,2025-06-12 22:28:08,2.0,1.0,
233,WHTLB25001854,WHTLB25001854-DO,2025-06-26T18:46:32,None,Kota Surabaya,2,23,22.84,WHTLAB,PT PASIFIK DISTRIBUSI INDONESIA,"Margomulyo No.65D, Greges, Kec. Asem Rowo, Sur...",PT Natura Deca Kosmetika,Completed,2025-06-27 02:43:07,2025-07-03 14:09:40,3.0,6.0,MISS

In [ ]:
df_merged['Entry_AWB'] = pd.to_datetime(df_merged['Entry_AWB'])

# Urutkan ASC (dari lama ke baru)
df_sort = df_merged.sort_values(by='Entry_AWB', ascending=True)

/tmp/ipython-input-4038527204.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_merged['Entry_AWB'] = pd.to_datetime(df_merged['Entry_AWB'])

In [ ]:
df_sort

,AWB_Resi,rdo_tracking_id,Entry_AWB,from_address2,to_l2,koli,rounded,nv_weight,nama_toko,Nama_Penerima,Alamat_Penerima,PT,granular_status,latest_ib_date,TGL_Sukses_Kiriman,SLA_Days,aging_days,verdict
4,WHTLB25001211,None,2025-04-28 17:09:56,Kota Jakarta Utara,Kota Jakarta Utara,3,15,14.75,WHTLAB,PT Aneka Kosmetindo Sejahtera,Jl sunter kemayoran no 126 sebelah sunter star...,PT SARI MELATI KENCANA TBK,Completed,2025-05-01 22:04:30,2025-05-02 12:58:36,2.0,1.0,
89,WHTLB25001212,None,2025-04-28 17:09:56,Kota Jakarta Utara,Kota Jakarta Barat,1,2,1.75,WHTLAB,Dianca Goods,PIC Syifa Jl Duri Tol No. 40A RT.06 RW.02 Kel ...,PT SARI MELATI KENCANA TBK,Completed,2025-04-29 16:25:23,2025-05-01 12:53:47,2.0,2.0,
99,WHTLB25001242,None,2025-04-29 16:43:08,Kota Jakarta Utara,Kota Jakarta Selatan,1,6,6.04,WHTLAB,Christian Cisse,"Apartment Puri Casablanca, Tower B, Unit 18-07...",PT NATURA DECA SENTOSA,Completed,2025-04-30 05:37:59,2025-05-01 13:42:46,2.0,1.0,
109,WHTLB25001316,None,2025-05-05 16:36:08,Kota Jakarta Utara,Kota Jakarta Utara,1,15,14.65,WHTLAB,PT Aneka Kosmetindo Sejahtera,Jl sunter kemayoran no 126 sebelah sunter star...,PT NATURA DECA SENTOSA,Completed,2025-05-06 03:58:17,2025-05-06 20:29:16,2.0,0.0,
198,WHTLB25001414A,None,2025-05-14 16:18:30,Kota Jakarta Utara,Kota Jakarta Utara,4,14,14.05,WHTLAB,PT Aneka Kosmetindo Sejahtera,Jl sunter kemayoran no 126 sebelah sunter star...,PT NATURA DECA SENTOSA,Completed,2025-05-15 18:12:01,2025-05-16 16:01:30,2.0,1.0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15,WHTLB25000417-EVENT,None,2025-09-04 15:56:47,None,Kota Cilegon,2,17,16.72,WHTLAB,Booth Cilegon Center Mall,"An. (Arie Diyah) Jl. Ahmad Yani, Sukmajaya, Ke...",PT CANTIK ALAM SENTOSA,Completed,2025-09-05 00:49:41,2025-09-06 12:19:44,2.0,1.0,
169,WHTLB25000418-EVENT,None,2025-09-04 15:56:47,None,Kab. Tangerang,1,3,3.10,WHTLAB,Booth Lippo Cikarang,An. (Afifah) Mall Lippo Cikarang Jl MH. Thamri...,PT CANTIK ALAM SENTOSA,Completed,2025-09-05 00:50:05,2025-09-05 11:32:03,2.0,0.0,
102,WHTLB25000412-EVENT,None,2025-09-04 15:56:47,None,Kota Denpasar,2,16,16.10,WHTLAB,Booth Bali,"An. (Alin) Level 21 Mall Jl. Teuku Umar No.1, ...",PT CANTIK ALAM SENTOSA,Completed,2025-09-08 14:52:18,2025-09-09 08:18:13,4.0,1.0,
214,WHTLBSTANDEE2,None,2025-09-04 15:56:48,None,Kota Tarakan,1,20,19.50,WHTLAB,Toko Four Shop Mulawarman,"An. (Rimannuloh) Jl. Mulawarman No.84, Karang ...",PT NATURA DECA KOSMETIKA,Arrived at Sorting Hub,2025-09-10 02:39:23,NaN,6.0,0.0,
174,WHTLBKIRIM-12SEPT2025,WHTLBKIRIM-12SEPT2025-DO,2025-09-08 10:13:19,None,Kota Surabaya,2,23,23.00,WHTLAB,PT PASIFIK DISTRIBUSI INDONESIA,"A.n (Ardhy) Jl.Margomulyo No.65D, Greges, Kec....",PT NATURA DECA KOSMETIKA,Arrived at Sorting Hub,2025-09-10 00:27:23,NaN,3.0,0.0,

## **Dumping Data to Google Sheet**

In [ ]:
import gspread as gs
from gspread_dataframe import set_with_dataframe

credentials = {
  "type": "service_account",
  "project_id": "ninjavanbiid",
  "private_key_id": "8fac04201c98dfa10ec7a73f1843e2280adaa618",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC5V/nhspBOJors\nsSRmcx0CQqd87MCvcZ5cn/iPe9zjZV9Z5A71JBUG6ORtvk9Ypek/JhGmvaDZKxe4\n7dquda+0VxIEkdFW+HWk/9sAVVbGuGs3m8cg7Mgviq0EqZ4+Rve99IsGDjX1hcdo\n9f/wAzqh8H5tw/5gxjuFqcrttuaE+tKfgicEGxggNf+hO6LFU6hsFMV8yVp7AsoR\nL3I5ZLk/RMspjWAf5HGzyLbPBJpW+5tES1JazjYvu1/BA+gj9q6C6bsnagnOE6+o\n1mkTq2PNgWLKYl9WILr0woC8HdtyFJIQ4lF8M/i82u2N2cCYF/d8UfFDvsKHBAk2\ni1Cfw/T9AgMBAAECggEAQ8fPo2Fo8puXzK2PkUPhxPTZSY9PfBnB/z+lZ9u1URe+\ngiIr8ixq4CcFerjRTasHHMfwRpksnJ7swv2BLrHtOrdo6HDnLLYaV+gVkA6leHDz\nDNgUP484OmKtmXnqW/4aFca7nNBPnWV6IoFsQrr7k0NfCQdXHM8B74TDqKFttg1f\nnBKTmCNsDTRS1FsMteYolxRb1o2Yb6YdycmpCATmaWkFxH7i8fS7x2f1oGckBqB0\nS3mkOI+gkxxOLU6qH/701k9jPhrcgpI/y12PsaPG6l2fJ2KCUXiNCQEa95/4J6k9\nWGTbbPIlTdfX6ZJNbQXmYIbFXXDt0KsaBC/2J6aAJQKBgQD3sX0EY8tDhQduTuIH\n9FJlveziBn8ThwgcjFknrLKfFBKIEgLmYW3ZcofTShcayiEzAA/hn8IJlShph9+w\nUGg4Vrte22GnRhrwa+y6/2VXmKwIxn8aZrQbYHnz7HcT+qU2KQCQ41tV+qgDDZPc\n39GFvv3lssZU253Hxt8fzD+qdwKBgQC/jzMfPkc4I5bnG2gLlHxbm6gAZhezeRWX\nFBG5ZLdU3AWBW9ScMWtfGPSc4+inrrqx9/fPLEr6qRzYJg47MdRJkzjCHflA5tBg\n1xrja3MmK9V+4GA5EYgBQ9R3JDzgOtic7VZ9o0Pft5n2LpnghcqnYHPNUCcf4awa\ntpYb1LIFKwKBgH+0Ha2uufS02JDx0K2jNPxJwKEEEm6B9xeo8Kp46psD4U4QYzhe\nUSGEYCz6jRD918IQrR95m7QPGAfYyuZ/fkxVw0LzvtRcW7VLH4GF/bz89O2NUajN\n/NwEkLvHVdmSJ63V0/nfjo60rfzs+igtqTvYrdTIqGLF3AJNMWqWhtifAoGAfzMZ\noT97jz2isKe0OSxKP5Jmxo0EY/qdaYq8Ej1ct466YSGXVnhCcg1iMOPt05rlAdRE\ny18AEt5E9wqeHJSEAK8v20aIAp7B8+wiQK1S8x/cTrmza3HGvABMjyiS+9pXiCzZ\nZ+gH5ABIzf43061D2kzj2IvGzxbNb5eaqbRc2a0CgYEAuRt6xVjiboMTB49hU3KD\nh3BfJ9gFeuvK8rH2fc44HB/TOlYXvlo/7V5EVn8Bxa2TStVt9b7fzjRTcS69A9yS\n91/qkH2FBYIutT27t15cE7+I/St68MkjlnCp4k+9BWnm1IKkXMpjvJEANEZJsAQ6\n5mJ/qaajzCsmemzVFegKAlU=\n-----END PRIVATE KEY-----\n",
  "client_email": "automation@ninjavanbiid.iam.gserviceaccount.com",
  "client_id": "100326913583619321970",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/automation%40ninjavanbiid.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
gc = gs.service_account_from_dict(credentials)

def connect_to_sheet(url):
    workbook = gc.open_by_url(url)
    return workbook

def connect_to_tab(url, tab_name):
    workbook = connect_to_sheet(url)
    tab = workbook.worksheet(tab_name)
    return tab

def clean_data(url, tab_name):
    workbook = connect_to_sheet(url)
    workbook.values_clear(f'{tab_name}')
    return print('Clean Succeed, Check your Gsheet')

import json
from datetime import time

def dump_data(data, url, tab_name, init_cell):
    workbook = connect_to_sheet(url)
    data = data.values.tolist()
    workbook.values_append(f'{tab_name}!'+init_cell,
                           {'valueInputOption': 'USER_ENTERED'},
                           {'values': data})
    return print('Dumping succeed, Check your Gsheet')

In [ ]:
# date_cols = ['Entry_AWB']  # sesuaikan dengan kolom kamu

# for col in date_cols:
#     df_sort[col] = pd.to_datetime(df_merged[col], errors='coerce').dt.strftime('%d/%m/%Y %H:%M')

In [ ]:
df_sort

,AWB_Resi,rdo_tracking_id,Entry_AWB,from_address2,to_l2,koli,rounded,nv_weight,nama_toko,Nama_Penerima,Alamat_Penerima,PT,granular_status,latest_ib_date,TGL_Sukses_Kiriman,SLA_Days,aging_days,verdict
4,WHTLB25001211,None,2025-04-28 17:09:56,Kota Jakarta Utara,Kota Jakarta Utara,3,15,14.75,WHTLAB,PT Aneka Kosmetindo Sejahtera,Jl sunter kemayoran no 126 sebelah sunter star...,PT SARI MELATI KENCANA TBK,Completed,2025-05-01 22:04:30,2025-05-02 12:58:36,2.0,1.0,
89,WHTLB25001212,None,2025-04-28 17:09:56,Kota Jakarta Utara,Kota Jakarta Barat,1,2,1.75,WHTLAB,Dianca Goods,PIC Syifa Jl Duri Tol No. 40A RT.06 RW.02 Kel ...,PT SARI MELATI KENCANA TBK,Completed,2025-04-29 16:25:23,2025-05-01 12:53:47,2.0,2.0,
99,WHTLB25001242,None,2025-04-29 16:43:08,Kota Jakarta Utara,Kota Jakarta Selatan,1,6,6.04,WHTLAB,Christian Cisse,"Apartment Puri Casablanca, Tower B, Unit 18-07...",PT NATURA DECA SENTOSA,Completed,2025-04-30 05:37:59,2025-05-01 13:42:46,2.0,1.0,
109,WHTLB25001316,None,2025-05-05 16:36:08,Kota Jakarta Utara,Kota Jakarta Utara,1,15,14.65,WHTLAB,PT Aneka Kosmetindo Sejahtera,Jl sunter kemayoran no 126 sebelah sunter star...,PT NATURA DECA SENTOSA,Completed,2025-05-06 03:58:17,2025-05-06 20:29:16,2.0,0.0,
198,WHTLB25001414A,None,2025-05-14 16:18:30,Kota Jakarta Utara,Kota Jakarta Utara,4,14,14.05,WHTLAB,PT Aneka Kosmetindo Sejahtera,Jl sunter kemayoran no 126 sebelah sunter star...,PT NATURA DECA SENTOSA,Completed,2025-05-15 18:12:01,2025-05-16 16:01:30,2.0,1.0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15,WHTLB25000417-EVENT,None,2025-09-04 15:56:47,None,Kota Cilegon,2,17,16.72,WHTLAB,Booth Cilegon Center Mall,"An. (Arie Diyah) Jl. Ahmad Yani, Sukmajaya, Ke...",PT CANTIK ALAM SENTOSA,Completed,2025-09-05 00:49:41,2025-09-06 12:19:44,2.0,1.0,
169,WHTLB25000418-EVENT,None,2025-09-04 15:56:47,None,Kab. Tangerang,1,3,3.10,WHTLAB,Booth Lippo Cikarang,An. (Afifah) Mall Lippo Cikarang Jl MH. Thamri...,PT CANTIK ALAM SENTOSA,Completed,2025-09-05 00:50:05,2025-09-05 11:32:03,2.0,0.0,
102,WHTLB25000412-EVENT,None,2025-09-04 15:56:47,None,Kota Denpasar,2,16,16.10,WHTLAB,Booth Bali,"An. (Alin) Level 21 Mall Jl. Teuku Umar No.1, ...",PT CANTIK ALAM SENTOSA,Completed,2025-09-08 14:52:18,2025-09-09 08:18:13,4.0,1.0,
214,WHTLBSTANDEE2,None,2025-09-04 15:56:48,None,Kota Tarakan,1,20,19.50,WHTLAB,Toko Four Shop Mulawarman,"An. (Rimannuloh) Jl. Mulawarman No.84, Karang ...",PT NATURA DECA KOSMETIKA,Arrived at Sorting Hub,2025-09-10 02:39:23,NaN,6.0,0.0,
174,WHTLBKIRIM-12SEPT2025,WHTLBKIRIM-12SEPT2025-DO,2025-09-08 10:13:19,None,Kota Surabaya,2,23,23.00,WHTLAB,PT PASIFIK DISTRIBUSI INDONESIA,"A.n (Ardhy) Jl.Margomulyo No.65D, Greges, Kec....",PT NATURA DECA KOSMETIKA,Arrived at Sorting Hub,2025-09-10 00:27:23,NaN,3.0,0.0,

In [ ]:
for col in df_merged.select_dtypes(include=['float64', 'datetime64', 'int64', 'object']).columns:
    df_sort[col] = df_sort[col].astype(str).replace(['nan', 'NaT', 'None'], '')

final_data_fix = df_sort.fillna('')


url_dump = url_dump
range_delete = "Master Data!A2:P40000"
clean_data(url_dump, range_delete)

url_dump = url_dump
tab_name_dump = "Master Data"
init_cell = "A2"
dump_data(final_data_fix, url_dump, tab_name_dump, init_cell)
print("Data Daily Whitelab already dump check data in template")

Clean Succeed, Check your Gsheet
Dumping succeed, Check your Gsheet
Data Daily Whitelab already dump check data in template

In [ ]:
# import pandas as pd
# from datetime import datetime

# # # Pastikan kolom tanggal dalam format datetime
# # # Parsing dengan format yang benar (dd/mm/yy HH:MM)
# # df_merged['TGL_Sukses_Kiriman'] = pd.to_datetime(df_merged['TGL_Sukses_Kiriman'], format='%d/%m/%y %H:%M', errors='coerce')
# # df_merged['latest_ib_date'] = pd.to_datetime(df_merged['latest_ib_date'], format='%d/%m/%y %H:%M', errors='coerce')
# # df_merged['SLA_Days'] = pd.to_numeric(df_merged['SLA_Days'], errors='coerce')

# # Buat fungsi hitung aging
# def calculate_aging(row):
#     if row['granular_status'] == 'Completed':
#         start_date = row['latest_ib_date'].date()
#         end_date = row['TGL_Sukses_Kiriman'].date()
#     else:
#         start_date = row['latest_ib_date'].date()
#         end_date = pd.Timestamp.now().date()
#     return (end_date - start_date).days

# # Hitung aging days
# df_merged['aging_days'] = df_merged.apply(calculate_aging, axis=1)

# # Tentukan verdict
# df_merged['verdict'] = df_merged.apply(
#     lambda row: 'MISS' if pd.notnull(row['aging_days']) and pd.notnull(row['SLA_Days']) and row['aging_days'] > row['SLA_Days']
#     else '',
#     axis=1
# )

# # (Optional) Filter hanya yang MISS
# df_miss_only = df_merged[df_merged['verdict'] == 'MISS']

# # Tampilkan hasil
# print(df_miss_only[['granular_status', 'latest_ib_date', 'TGL_Sukses_Kiriman', 'aging_days', 'SLA_Days', 'verdict']])